[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "streamsync"
authors = [{ name = "Ramiro Medina", email = "ramiro.a.medina@gmail.com" }]
description = "Streamsync helps you create performant data apps, via Python code and its built-in visual UI editor."
readme = "README.md"
requires-python = ">=3.9.2"
keywords = ["data apps", "gui", "ui"]
license = { text = "Apache 2.0" }
classifiers = ["Development Status :: 4 - Beta"]
dependencies = [
    "pydantic >= 2.6.0, < 3",
    "fastapi >= 0.89.1, < 1",
    "websockets >= 12, < 13",
    "uvicorn >= 0.20.0, < 1",
    "watchdog >= 3.0.0, < 4"
]

dynamic = ["version"]

[project.optional-dependencies]
ds = [
    "pandas >= 2.2.0, < 3",
    "pyarrow >= 15.0.0, < 16.0.0",
    "plotly >= 5.18.0, < 6"
]
test = [
    "pandas >= 2.2.0, < 3",
    "pyarrow >= 15.0.0, < 16.0.0",
    "plotly >= 5.18.0, < 6",
    "pytest-asyncio >= 0.23.4, < 1",
    "pytest >= 7.0.0, < 8",
    "altair >= 5.2.0, < 6", 
    "httpx >= 0.26.0, < 1"
]
build = [
    "pandas >= 2.2.0, < 3",
    "pyarrow >= 15.0.0, < 16.0.0",
    "plotly >= 5.18.0, < 6",
    "build >= 1.0.3, < 2",
    "mypy >= 1.8.0, < 2",
    "pandas-stubs >= 2.0.0, <3",
    "pytest >= 8.0.0, < 9",
    "pytest-asyncio >= 0.23.4, < 1",
    "altair >= 5.2.0, < 6", 
    "httpx >= 0.26.0, < 1"
]

[project.urls]
Home = "https://www.github.com/streamsync-cloud/streamsync"

[project.scripts]
streamsync = "streamsync.command_line:main"

[tool.setuptools.dynamic]
version = { attr = "streamsync.VERSION" }
