[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "streamsync"
authors = [{ name = "Ramiro Medina", email = "ramiro.a.medina@gmail.com" }]
description = "Streamsync helps you create performant data apps, via Python code and its built-in visual UI editor."
readme = "README.md"
requires-python = ">=3.9.2"
keywords = ["data apps", "gui", "ui"]
license = { text = "Apache 2.0" }
classifiers = ["Development Status :: 3 - Alpha"]
dependencies = [
    "fastapi >= 0.89.1, < 1",
    "websockets >= 10.4, < 11",
    "uvicorn >= 0.20.0, < 1",
    "watchdog >= 2.2.1, < 3"
]

dynamic = ["version"]

[project.optional-dependencies]
ds = [
    "pandas >= 1.5.3, < 2",
    "plotly-express >= 0.4.1, < 1"
]
test = [
    "pandas >= 1.5.3, < 2",
    "plotly-express >= 0.4.1, < 1"
    "pytest >= 7.0.0, < 8",
    "altair >= 4.1.0, < 5", 
    "httpx >= 0.18.2, < 1"
]
build = [
    "pandas >= 1.5.3, < 2",
    "plotly-express >= 0.4.1, < 1"
    "build >= 0.7.0, < 1",
    "mypy >= 0.900, < 2",
    "pytest >= 7.0.0, < 8",
    "altair >= 4.1.0, < 5",
    "httpx >= 0.18.2, < 1"
]

[project.scripts]
streamsync = "streamsync.command_line:main"

[tool.setuptools.dynamic]
version = { attr = "streamsync.VERSION" }
