name: docs

on:
  push:
    branches:
      - 'master'

jobs:
  trigger-mintlify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger mintlify workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DOCS_WORKFLOW_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'anant-writer',
              repo: 'docs',
              workflow_id: 'mintlify-action.yml',
              ref: 'main',
            });
