name: E2E Tests
on:
  push:
    branches: [ dev, master]
  pull_request: 
    branches: [ dev, master]

jobs:
  chromium:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.8"

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: update package manager & install python3 environment
        run: |
          sudo pip install poetry
          poetry install --with build

      - name: Install npm dependencies
        run: npm ci

      - name: Build UI
        run: npm run build

      - name: Install E2E browsers
        working-directory: e2e_tests 
        run: npx playwright install --with-deps
      - name: Run E2E tests
        run: poetry run alfred ci --e2e=chromium

  firefox:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.8"

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: update package manager & install python3 environment
        run: |
          sudo pip install poetry
          poetry install --with build

      - name: Install npm dependencies
        run: npm ci

      - name: Build UI
        run: npm run build

      - name: Install E2E browsers
        working-directory: e2e_tests 
        run: npx playwright install --with-deps
      - name: Run E2E tests
        run: poetry run alfred ci --e2e=firefox

  webkit:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.8"

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: update package manager & install python3 environment
        run: |
          sudo pip install poetry
          poetry install --with build

      - name: Install npm dependencies
        run: npm ci

      - name: Build UI
        run: npm run build

      - name: Install E2E browsers
        working-directory: e2e_tests 
        run: npx playwright install --with-deps
      - name: Run E2E tests
        run: poetry run alfred ci --e2e=webkit
