name: publish

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - 'v[0-9]+.[0-9]+.[0-9]+[a-z0-9]*'

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2

            - name: update package manager & install python3 environment
              run: |
                pip install poetry
                poetry install

            - name: run continuous integration to check everything is fine
              run: |
                poetry run alfred ci

            - name: publish on pypi
              run: |
                poetry run alfred publish.pypi
              env:
                  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
